require 'pry'
require 'open-uri'
require 'nokogiri'
require 'word_wrap'
require 'colorize'

require_relative './headlines_today/version'
require_relative './headlines_today/cli'
require_relative './headlines_today/headline'
require_relative './headlines_today/scraper'
